DROP SCHEMA CLIENTESIMULACAO CASCADE;

CREATE SCHEMA CLIENTESIMULACAO;

CREATE TABLE CLIENTESIMULACAO.TB_ENDERECO
(
    ID_ENDERECO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUA         VARCHAR(250),
    NUMERO      INTEGER,
    BAIRRO      VARCHAR(100),
    CEP         VARCHAR(8),
    CIDADE      VARCHAR(100),
    ESTADO      VARCHAR(2)
);

CREATE TABLE CLIENTESIMULACAO.TB_CLIENTE
(
    ID_CLIENTE  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CPF         VARCHAR(11),
    NOME        VARCHAR(200),
    ID_ENDERECO BIGINT,
    CONSTRAINT FK_CLIENTE_ENDERECO
        FOREIGN KEY (ID_ENDERECO)
            REFERENCES CLIENTESIMULACAO.TB_ENDERECO (ID_ENDERECO)
);

CREATE TABLE CLIENTESIMULACAO.TB_SIMULACAO
(
    ID_SIMULACAO     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE       BIGINT,
    CREATED_AT       TIMESTAMP,
    VALOR_SOLICITADO NUMERIC(20, 6),
    VALOR_GARANTIA   NUMERIC(20, 6),
    QTD_MESES        INTEGER,
    TX_JUROS_MENSAL  NUMERIC(10, 10),
    CONSTRAINT FK_SIMULACAO_CLIENTE
        FOREIGN KEY (ID_CLIENTE)
            REFERENCES CLIENTESIMULACAO.TB_CLIENTE (ID_CLIENTE)
)